### ISSUE TITLE
Proposed Issue templates for BioModels Annotation and Incorporation

### ISSUE THREAD

**Issue by Zainab-ik** [ersilia-os/eos80ch#4]
Hi @GemmaTuron @miquelduranfrigola 

Here is an issue [template](https://github.com/Zainab-ik/Creating-issue-templates/blob/main/.github/ISSUE_TEMPLATE/config.yml) for to incorporate BioModel annotations and information into Ersilia. 

Below are the different sections ;

- **Model name**: BioModel uses a one-liner approach to describe a model e.g. first author, year, model activity. Reference - or example; Swanson2023 - ADMET Properties Predictions
- **Model Identifier**; For each curated model incorporated or uploaded into the BioModels repository, an ID number is generated, e.g., BIOMD0000000100
- **Tag**: All machine learning models in the BioModels repository have the FAIR AIML tag, this applies to the findability, accesibility, interoperability (model exchange) and reusability of the models. 
- **Metadata Information**: This part describes the metadata extracted manually from the paper or auto-generated, challenges and clarification regarding its annotation. 
- **Contributor**: The modeller, reviewer, and the curator of the model will be acknowledged.
- **Curation Status**: Metadata are curated either manually or AI generated. This section would identify that.
- **Annotation file**: The annotation files of the metadata should be linked to the model for accesibility
- **BioModel Link**: After uploading a model into the BioModels repository, a link is generated which should be attached to the Ersilia model. e.g., https://www.ebi.ac.uk/biomodels/MODEL1907310001

**Comment by miquelduranfrigola** [comment]
Thank you @Zainab-ik

**Comment by GemmaTuron** [comment]
Hi @Zainab-ik,

Thanks, this is useful. I would though think about having TWO separate issues that allow us to work in a two-stage process. First, to decide which data will go into the annotation, and second, to collect all relevant information (some of it won't be ready until the model has been submitted to biomodels, for example the link)

1. Discussion issue: a place where we can talk about the information added to each model. From the fields you provide, this would be Model Name, Tags, Metadata Information, Contributor, Curation Status
2. Biomodel information issue: here we will have a form that can be automatically parsed to collect the relevant data, including all the above and model identifier, biomodel link. Those won't be ready until the model is uploaded

Does this make sense?

**Comment by Zainab-ik** [comment]
> Hi @Zainab-ik,
> 
> Thanks, this is useful. I would though think about having TWO separate issues that allow us to work in a two-stage process. First, to decide which data will go into the annotation, and second, to collect all relevant information (some of it won't be ready until the model has been submitted to biomodels, for example the link)
> 
> 1. Discussion issue: a place where we can talk about the information added to each model. From the fields you provide, this would be Model Name, Tags, Metadata Information, Contributor, Curation Status
> 2. Biomodel information issue: here we will have a form that can be automatically parsed to collect the relevant data, including all the above and model identifier, biomodel link. Those won't be ready until the model is uploaded
> 
> Does this make sense?

This makes perfect sense. 
Do I go ahead and modify the templates?

**Comment by GemmaTuron** [comment]
yes, let's use these two models we are working on as example and after that we can refine the Discussion template. Once we have done about 10 models, we can refine the Biomodel information template

**Comment by Zainab-ik** [comment]
Alright,
I've modified the template to create the one for [discussion](https://github.com/Zainab-ik/Creating-issue-templates/blob/main/.github/ISSUE_TEMPLATE/discussion.yml).

I retained the first one to serve as the Information issue.

**Comment by Zainab-ik** [comment]
Hi @GemmaTuron 

How does this looks [discussion around eos80ch](https://github.com/ersilia-os/eos80ch/issues/5)

**Comment by DhanshreeA** [comment]
@GemmaTuron this one as well - good to close?
