### ISSUE TITLE
BioModel Discussion Issue for eos80ch

### ISSUE THREAD

**Issue by Zainab-ik** [ersilia-os/eos80ch#5]
Here is the [discussion issue template](https://github.com/Zainab-ik/Creating-issue-templates/blob/main/.github/ISSUE_TEMPLATE/discussion.yml).

Below is a sample specific to _**eos80ch**_

- **BioModel Name**: van-Heerden2023,  Chemical Features Identification for Stage-Specific Antimalarial Compounds
- **BioModel Tag**: fair AIML
- **Metadata Information**: These are the metadata extracted from the paper

> 
| Ontologies            | Metadata | 
| :---------------- | :------: | 
| Ontology for Parasite Lifecycle OPL        |   asexual lifecycle in host red blood cell stage  | 
| Experimental Factor Ontology EFO         |   Malaria   | 

- **Contributor**:

> 
| roles             | Names | 
| :---------------- | :------: | 
| Curator        |   @Zainab-ik   | 
| Code contributor       |   @GemmaTuron    | 
| Reviewer       |   @GemmaTuron    | 

- **Curation status** :  manually curated
- **Annotation file**: 
[eos80ch](https://docs.google.com/spreadsheets/d/1hUtSjuOOAXDQrL77mIsCQumaW4TVel076qrkXq79nSk/edit?usp=drive_link)

- **BioModel Upload**:  https://www.ebi.ac.uk/biomodels/MODEL2403270002

**Comment by Zainab-ik** [comment]
The annotation for this model is complete and after review would be uploaded to BioModels tomorrow.

**Comment by GemmaTuron** [comment]
Hi @Zainab-ik 

This looks good, might I ask why there is so few ontologies when in the .csv there are many more? I understand it can be annoying to copy everything from the .csv to the issue, which I do not think is necessary. My suggestion would be:
- In the metadata annotation, use the field to summarise your findings and ask any questions, note down any points for discussion. For example: I am not sure if this model is related to the sexual or asexual cycle of the parasite
- In the .csv file: I'd prefer a link to the .csv file in our Drive, so I don't have to download it and can check directly online if that sounds good?
- About the tags: is there a place where I can look for all the tags? Fair ML looks good, but are there other more specific tags, or not?

Let me know your thoughts on those, and also if you have any specific doubt about eos80ch before we approve it!

**Comment by Zainab-ik** [comment]
Hi @GemmaTuron 

Thank you. 
Yes, I just copied a few as sample since there's the annotation file. 

- Noted for the metadata annotation. I'd implement that for the rest of the model if that sounds good. 
- CSV link changed to the one in the drive.
- For the tags, I've made enquiry. There's just 2 tags used for ML models which are _FAIR AIML_ and _machine learning_ models. I'd get back regarding this when i get a response. 

Foe _eos80ch_, I do not have any specific doubt. I've cleared it all with @miquelduranfrigola

**Comment by Zainab-ik** [comment]
I'm having a difficulty uploading the file to the drive as a google sheet file. 
I opened with google sheet, download as a CSV, and upload to the drive as a CSV. However, it's still showing as a CSV file on the drive rather than a google sheet file.

**Comment by GemmaTuron** [comment]
Hi @Zainab-ik 

Yes, google drive is a bit particular - once you open a file as a google sheet, you always need to use that. Only download it when it is ready as a .csv file, as if you re-upload it, you will have to convert it again.
So, I suggest instead of downloading it, just pasting the link to the google sheet here, as it will then always redirect to the file which can be dynamically updated

**Comment by Zainab-ik** [comment]
Hi @GemmaTuron 

I think this is good, right?

**Comment by DhanshreeA** [comment]
@GemmaTuron is this issue good to close?
